auth_enabled: false

server:
  http_listen_port: 9009
  grpc_listen_port: 9095

common:
  path_prefix: /var/lib/mimir
  storage:
    backend: filesystem
    filesystem:
      dir: /var/lib/mimir/data

blocks_storage:
  backend: filesystem
  tsdb:
    dir: /var/lib/mimir/tsdb
  bucket_store:
    sync_dir: /var/lib/mimir/tsdb-sync

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1

ruler:
  rule_path: /var/lib/mimir/rules

limits:
  ingestion_rate: 200000
  ingestion_burst_size: 200000
