multitenancy_enabled: false

server:
  http_listen_port: 9009
  grpc_listen_port: 9095

memberlist:
  abort_if_cluster_join_fails: false
  bind_addr:
    - 0.0.0.0
  bind_port: 7946

blocks_storage:
  backend: filesystem
  filesystem:
    dir: /var/lib/mimir/blocks
  tsdb:
    dir: /var/lib/mimir/tsdb
  bucket_store:
    sync_dir: /var/lib/mimir/tsdb-sync

ingester:
  ring:
    replication_factor: 1

ruler:
  rule_path: /var/lib/mimir/ruler

ruler_storage:
  backend: filesystem
  filesystem:
    dir: /var/lib/mimir/rules

limits:
  ingestion_rate: 200000
  ingestion_burst_size: 200000
