receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch: {}

connectors:
  spanmetrics:
    metrics_flush_interval: 5s
    dimensions:
      - name: http.method
      - name: http.route
      - name: http.status_code

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
  otlphttp/tempo:
    endpoint: http://tempo:4318
  prometheusremotewrite/mimir:
    endpoint: http://mimir:9009/api/v1/push

service:
  telemetry:
    metrics:
      address: 0.0.0.0:8888
  pipelines:
    metrics:
      receivers: [otlp, spanmetrics]
      processors: [batch]
      exporters: [prometheus, prometheusremotewrite/mimir]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/tempo, spanmetrics]
